### ISSUE TITLE
Oauth. 

### ISSUE THREAD

**Issue by chrisamoore** [xgeoff/CloudFirestoreDataLoader#1]
When I attempt to sign in with google I get some oauth issue, can you add instructions for this ? 

![screenshot 2018-01-10 19 35 34](https://user-images.githubusercontent.com/740153/34807402-7f219372-f63d-11e7-9d1b-d9b74575bb4d.png)

**Comment by xgeoff** [comment]
Hmmm... weird. Somehow Firebase is looking at your local hosting IP. It doesn't do that to me, but I'm not sure why. I run my project from NetBeans and I'm wondering if it is using something other than the local IP. See if you can set your server to use an IP different than 127.0.0.1. For example, try changing the url to 'localhost' instead.
